In [1]:
import pandas as pd
import numpy as np

## Recommendation System

<img src='https://miro.medium.com/max/2048/1*VpYW2bpFIpnxAPbXTL27ag.png' width=80%>

### Content-Based Filtering

Rekomendasi diberikan berdasarkan features dari item yang disukai user

In [2]:
produk = [
    'Gundam Doraeman Tsubasa',
    'Gundam Gundam Gundam'
]

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
extractor = CountVectorizer()
exfit = extractor.fit_transform(produk)
exfit

<2x3 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [10]:
extractor.get_feature_names()

['doraeman', 'gundam', 'tsubasa']

In [11]:
exfit.toarray()

array([[1, 1, 1],
       [0, 3, 0]], dtype=int64)

In [12]:
# cosinus similarity
from sklearn.metrics.pairwise import cosine_similarity
score = cosine_similarity(exfit)
score

#       x[0]          x[1]
# x[0]   1.        0.57735027
# x[1] 0.57735027      1.

array([[1.        , 0.57735027],
       [0.57735027, 1.        ]])

In [13]:
df = pd.DataFrame([
    {'title': 'A', 'genre': 'Pop', 'label': 'PT. A'},
    {'title': 'B', 'genre': 'Keroncong', 'label': 'PT. A'},
    {'title': 'C', 'genre': 'Dangdut', 'label': 'PT. A'},
    {'title': 'D', 'genre': 'Pop', 'label': 'PT. B'},
    {'title': 'E', 'genre': 'Keroncong', 'label': 'PT. B'},
    {'title': 'F', 'genre': 'Dangdut', 'label': 'PT. B'},
    {'title': 'G', 'genre': 'Pop', 'label': 'PT. C'},
    {'title': 'H', 'genre': 'Keroncong', 'label': 'PT. C'},
    {'title': 'I', 'genre': 'Dangdut', 'label': 'PT. C'},
    {'title': 'J', 'genre': 'Pop', 'label': 'PT. C'}
])
df

title      genre  label
0     A        Pop  PT. A
1     B  Keroncong  PT. A
2     C    Dangdut  PT. A
3     D        Pop  PT. B
4     E  Keroncong  PT. B
5     F    Dangdut  PT. B
6     G        Pop  PT. C
7     H  Keroncong  PT. C
8     I    Dangdut  PT. C
9     J        Pop  PT. C

In [16]:
ecv = CountVectorizer()
mgenre = ecv.fit_transform(df['genre'])
ecv.get_feature_names()

['dangdut', 'keroncong', 'pop']

In [17]:
mgenre.toarray()

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int64)

In [19]:
cosScore = cosine_similarity(mgenre)
cosScore

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [29]:
# ada user suka produk index = 0
produkMirip = list(enumerate(cosScore[0]))
produkMirip = sorted(produkMirip, key = lambda x: x[1], reverse=True)
produkMirip[:5]

[(0, 1.0), (3, 1.0), (6, 1.0), (9, 1.0), (1, 0.0)]

In [30]:
for i in produkMirip[:5]:
    print(df.iloc[i[0]])

title        A
genre      Pop
label    PT. A
Name: 0, dtype: object
title        D
genre      Pop
label    PT. B
Name: 3, dtype: object
title        G
genre      Pop
label    PT. C
Name: 6, dtype: object
title        J
genre      Pop
label    PT. C
Name: 9, dtype: object
title            B
genre    Keroncong
label        PT. A
Name: 1, dtype: object
